name: Build

# Recommended permissions, see also:
# - https://github.com/actions/setup-go?tab=readme-ov-file#recommended-permissions

permissions:
  contents: read

on:
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: ubuntu-latest
            GOOS: linux
            GOARCH: amd64
            EXT: ""
          - os: windows-latest
            GOOS: windows
            GOARCH: amd64
            EXT: ".exe"
          - os: macos-latest
            GOOS: darwin
            GOARCH: amd64
            EXT: ""

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          # We need full git history so that the build process can embed it
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          # Flag to enable caching of dependencies
          cache: true

          # Use the same version of Go as defined by the project
          go-version-file: go.mod

          # Target architecture that we want to compile to
          architecture: ${{ matrix.GOARCH }}

      - name: Download Dependencies
        run: go mod tidy

      - name: Build Binary
        run: |
          GOOS=${{ matrix.GOOS }} go build -o faf-pioneer-snapshot-${{ matrix.GOOS }}-${{ matrix.GOARCH }}${{ matrix.EXT }} ./cmd/faf-adapter

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: faf-pioneer-snapshot-${{ matrix.GOOS }}-${{ matrix.GOARCH }}
          path: faf-pioneer-snapshot-${{ matrix.GOOS }}-${{ matrix.GOARCH }}${{ matrix.EXT }}
